function overworldFunction() {
    document.getElementById("table").innerHTML =
    /* Titles */"<tr><td>Overworld Mob Picture</td><td>Health</td><td>Aggression Status</td><td>Natural Spawn</td><td>Other Info</td></tr>" +
    /* Axolotl */"<tr><td><img src='/images/axolotl.avif' alt='axolotl'><p>Axolotl</p></td><td>7 hearts</td><td>Passive<p>Hostile with fish and drowned</p></td><td>Lush Caves</td><td>Can be picked up in a bucket<p>Can grant play dead and possibly gain regeneration</p></td></tr>" +
    /* Bat */"<tr><td><img src='/images/bat.jpg' alt='bat'><p>Bat</p></td><td>3 hearts</td><td>Passive</td><td>Anywhere with light level 3 or under</td><td>Don't drop anything when killed</td></tr>" +
    /* Bee */"<tr><td><img src='/images/bee.jpg' alt='bee'><p>Bee</p></td><td>5 hearts</td><td>Neutral<p>Hostile with anything that damages the bee or the hive without a campfire under it</p></td><td>Spawns with beehive in:<p>Medow, Plains, Sunflower Plains, Mangrove Swamp, Flower Forest, Forest, Birch Forest, Old Growth Birch Forest & Cherry Grove</p></td><td>Takes pollen from nearby flowers and takes back to hive, pollen dripping from bees speed up crop growth<p>When bee is hostile with player eyes turn red and attempts to stings player. If the bee stings a player, the player is poisoned and the bee dies after roughly 1 minute</p></td></tr>" +
    /* Bogged */"<tr><td><img src='/images/bogged.jpg' alt='bogged'><p>Bogged</p></td><td>8 hearts</td><td>Hostile</td><td>Swamps & mangrove swamps, or from trial spawners in trial chambers</td><td>Shoots arrows tipped with poison<p>Can drop bones, normal arrows and/or posioned arrows</p></td></tr>" +
    /* Breeze */"<tr><td><img src='/images/breeze.jpg' alt='breeze'><p>Breeze</p></td><td>15 hearts</td><td>Hostile</td><td>Spawn from trial spawners in trial chambers</td><td>Shoots wind charges, which can open close trapdoors and doors, knock any mob or player up a few blocks and press buttons and preasure plates<p>Drops breeze rods when killed</p></td></tr>" +
    /* Cat */"<tr><td><img src='/images/cats.webp' alt='cat'><p>Cat</p></td><td>5 hearts</td><td>Passive<p>Hostile with rabbits & baby turtles</p></td><td>Villages or swamp hut(Black varient only)</td><td>Untamed cats are scared of players<p>Can be tamed with raw fish</p><p>Scares creepers away</p></td></tr>" +
    /* Cave Spider */"<tr><td><img src='/images/caveSpider.jpg' alt='cave spider'><p>Cave Spider</p></td><td>6 hearts</td><td>Hostile in light level 11 and under<p>Neutral in light level 12 and under</p></td><td>Spawned by mob spawners in mineshafts, trial chambers and dungeons</td><td>If they attack a player, inflicts poison</td></tr>" +
    /* Chicken */"<tr><td><img src='/images/chickens.jpg' alt='chicken'><p>Chicken</p></td><td>2 hearts</td><td>Passive</td><td>All all biomes barring any desert, snowy, icey, water or underground biome. The only exception is that the cold varients do spawn in Snowy Taigas </td><td>Yellow varient spawns in warm biomes<p>White varient spawns in temperate biomes</p><p>Dark grey varient spawns in cold biomes</p></td></tr>" +
    /* Cod */"<tr><td><img src='/images/cod.jpg' alt='cod'><p>Cod</p></td><td>1.5 hearts</td><td>Passive</td><td>Cold and temperate oceans and rivers</td><td>Can be picked up in a bucket<p>Sometimes drop bonemeal when killed</p></td></tr>" +
    /* Cow */"<tr><td><img src='/images/cows.jpg' alt='cow'><p>Cow</p></td><td>5 hearts</td><td>Passive</td><td>Spawn in all the same biomes as cows</td><td>Brown and white varient spawns in warm biomes<p>Dark brown and white-spotted spawns in temperate biomes</p><p>Long-haired, light brown varient spawns in cold biomes</p></td></tr>" +
    /* Creaking */"<tr><td><img src='/images/creaking.jpg' alt='creaking'><p>Creaking</p></td><td> 0.5 a heart</td><td>Hostile</td><td>During nighttime or during a thunderstorm within 16 blocks of their creaking heart. These hearts occur naturally in the middle of a pale oak tree</td><td>Doesn't take damage when it, it can only be killed by breaking its creaking heart<p>Cannot move when a player is looking at it</p><p>Doesn't drop anything upon death</p></td></tr>" +
    /* Creeper */"<tr><td><img src='/images/creeper.jpeg' alt='creeper'><p>Creeper</p></td><td>10 hearts</td><td>Hostile</td><td>Anywhere with a light level of 0 barring mushroom fields & deep dark</td><td>If struck by lightling, can become a charged creeper and do a lot more damage<p>Scared of cats</p><p>Drop gunpowder when killed</p></td></tr>" +
    /* Dolphin */"<tr><td><img src='/images/dolphin.jpg' alt='dolphin'><p>Dolphin</p></td><td>5 hearts</td><td>Neutral</td><td>Temperate and warm ocen biomes</td><td>If a player is within 15 blocks, they will gain dolphin's grace for a short period of time<p>If fed salmon or cod, they will lead a player to a shipwreak or ocean ruins</p><p>Avoid guardians and elder guardians</p><p>Will die if left out of water for too long</p></td></tr>" +
    /* Donkey */"<tr><td><img src='/images/donkey.jpg' alt=''donkey><p>Donkey</p></td><td>Ranges form 7.5 to 15 hearts</td><td>Passive</td><td>Savanna biomes, plains biomes and meadows</td><td>Can be tamed, saddled and chested<p>Along with health varying, speed and jump height varies</p></td></tr>" +
    /* Drowned */"<tr><td><img src='/images/drowned.jpg' alt=''drowned><p>Drowned</p></td><td>10 hearts</td><td>Neutral during day if no player touches water nearby the drowned<p>Hostile to axolotls and players during the night</p></td><td>In all bodies of water with light level 0</td><td>Burn in daylight unless they're in water<p>Can sometimes spawn with a trident which they will throw to attack</p><p>Zombies can be converted to drowned if they drown in water</p></td></tr>" +
    /* Evoker*/"<tr><td><img src='/images/evoker.jpg' alt='evoker'><p>Evoker</p></td><td>12 hearts</td><td>Hostile</td><td>Woodland mansions or during raids</td><td>Spawn vexes and ranged jaws attack when a evoker sees a player<p>Drops a totem of undying when killed, which can resurrect a player from death when they're holding it in their hand</p></td></tr>" +
    /* Fox */"<tr><td><img src='/images/foxes.jpg' alt='fox'><p>Fox</p></td><td>5 hearts</td><td>Passive when wild<p>When it trusts a player it's neutral to other players</p></td><td>Taigas, old growth pine taigas & old growth spruce taigas (red varient)<p>Groves and snowy taigas (white varient)</p></td><td>Can gain trust by feeding it sweet berries<p>Will steal items left on the grown near it</p><p>Scared of players when its wild, and of wolves and polar bears</p></td></tr>" +
    /* Goat */"<tr><td><img src='/images/goat.jpg' alt='goat'><p>Goat</p></td><td>5 hearts</td><td>Neutral (will occasionally try to ram an entity, but passive otherwise)</td><td>Frozen peaks, jagged peaks & snowy slopes</td><td>2% chance of a goat spawning in as a screaming goat, which look identical to other goats except for the fact they scream<p>Drops goat horn when it rams into a naturally-generated solid block</p></td></tr>" +
    /* Guardian*/"<tr><td><img src='/images/guardian.jpg' alt='guardian'><p>Guardian</p></td><td>15 hearts</td><td>Hostile</td><td>In water around ocean monuments</td><td>Attacks with a lazer that takes 2 seconds to charge up or with spike defense when hit with a melee attack</td></tr>" +
    /* Horses */"<tr><td><img src='/images/horses.jpg' alt='horse'><p>Horse</p></td><td>Ranges form 7.5 to 15 hearts</td><td>Passive</td><td>Plains, sunflower plains, savanna, savanna plateau, windswept savanna & villages</td><td>Can be tammed, saddled and armored<p>Along with health varying, speed and jump height varies</p></td></tr>" +
    /* Husk */"<tr><td><img src='/images/husk.jpg' alt='husk'><p>Husk</p></td><td>10 hearts</td><td>Hostile</td><td>Desert biome at light level 0 or from trial spawners in trial chambers</td><td>When they attack they apply hunger to their target<p>They don't burn in daylight</p></td></tr>" +
    /* Iron Golem */"<tr><td><img src='/images/ironGolem.jpg' alt='iron golem'><p>Iron Golem</p></td><td>50 hearts</td><td>Neutral (when naturally spawned)<p>Passive (when player-built)</p></td><td>Nautally spawns in villages or cages in pillager outposts<p>Can be built by players. Build a T-shape with 4 iron blocks and add a carved pumpkin on of the top-center iron block</p></td><td>Can be spawned by panicking villagers<p>Slow, but powerful. Throws target up into the air with attack</p><p>Can drop iron and poppies upon death</p></td></tr>" +
    /* Llama */"<tr><td><img src='/images/llamas.jpg' alt=''llama><p>Llama</p></td><td>Rage from 7.5 to 15 hearts</td><td>Neutral<p>Hostile towards untamed wolves</p></td><td>All windswept biomes, savanna and savanna plateau</td><td>Can put different-colored carpets on top of llamas to ride them but not control them<p>You can also chest them to use them for storage</p></td></tr>" +
    /* Mooshroom */"<tr><td><img src='/images/mooshrooms.jpg' alt='mooshroom'><p>Mooshroom</p></td><td>5 hearts</td><td>Passive</td><td>Mushroom fields (red varient only)</td><td>The brown varient is created by striking a red varient with lighting<p>Mooshrooms can be milked with bowls to get mushroom soup</p><p>Can also be sheared to get a normal cow</p></td></tr>" +
    /* Mule */"<tr><td><img src='/images/mule.jpg' alt='mule'><p>Mule</p></td><td>Rage from 7.5 to 15 hearts</td><td>Passive</td><td>Don't naturally spawn. Are created by breeding a horse & a donkey</td><td>Can be tammed, saddled and chested<p>Along with health varying, speed and jump height varies</p><p>Cannot be bred with other mules, donkeys or horses at all</p></td></tr>" +
    /* Ocelot */"<tr><td><img src='/images/ocelot.jpg' alt='ocelot'><p>Ocelot</p></td><td>5 hearts</td><td>Passive<p>Hostile towards chickens & baby turtles</p></td><td>Jungles</td><td>Scared of players, but they scare creepers away</td></tr>" +
    /* Panda */"<tr><td><img src='/images/pandas.jpg' alt='panda'><p>Panda</p></td><td>10 hearts</td><td>Neutral</td><td>Jungle & bamboo jungle</td><td>Baby pandas have a 1 in 700 to drop a slimeball when they sneeze and scare all adult pandas around them when they do sneeze<p>Pandas have different personalities depending on their face</p></td></tr>" +
    /* Parrot */"<tr><td><img src='/images/parrots.jpg' alt='parrot'><p>Parrot</p></td><td>3 hearts</td><td>Passive</td><td>Jungle & bamboo jungle</td><td>Cookies are toxtic to parrots<p>Can be tamed and sit on an empty shoulder of a player</p><p>Can imitate the sounds of most mobs if they're nearby</p></td></tr>" +
    /* Phantom */"<tr><td><img src='/images/phantom.jpg' alt='phantom'><p>Phantom</p></td><td>10 hearts</td><td>Hostile/td><td>At nighttime or during a thunderstorm when a player hasn't slept or dies for 3 in-game days</td><td> Only flys, phantoms swoop down to attack a player, it never touches the ground<p>Healed by any damaging potions and hurt by any healing potions</p><p>Burns in daylight and drops phantom membrane when killed</p></td><tr>" +
    /* Polar Bear */"<tr><td><img src='/images/polarBear.jpg' alt='polar bear'><p>Polar Bear</p></td><td>15 hearts</td><td>Neutral<p>Hostile (adult with cubs)</p></td><td>Snowy plains, ice spikes, frozen ocean and deep frozen ocean</td><td>When killed can drop raw cod and/or raw salmon</td></tr>" +
    /* Ravager */"<tr><td><img src='/images/ravager.jpg' alt='raveger'><p>Ravager</p></td><td>50 hearts</td><td>Hostile</td><td>Raids</td><td> Tramples all crops planted in farmed land a ravager walks across<p>Can be ridden by pillagers during raids</p></td></tr>" +
    /* Salmon */"<tr><td><img src='/images/salmon.png' alt='salmon'><p>Salmon</p></td><td>1.5 hearts</td><td>Passive</td><td>Cold oceans and rivers</td><td>Can be picked up in a bucket<p>Sometimes drop bonemeal when killed</p></td></tr>" +
    /* Sheep */"<tr><td><img src='/images/sheep.jpg' alt='sheep'><p>Sheep</p></td><td>4 hearts</td><td>Passive</td><td>Almost all overworld biomes with grass</td><td>16 different colors a sheep can be dyed<p>If a sheep is named 'jeb_'</p></td></tr>" +
    /* Silverfish */"<tr><td><img src='/images/silverfish.jpg' alt='sivlerfish'><p>Silverfish</p></td><td>4 hearts</td><td>Hostile</td><td>In the stronghold from mob spawners<p>After mining naturally-generated infested stone</p><p>From trial spawners in the trial chambers</p><p>Spawned from an entity who has the infested potion effect and takes damage</p></td><td>Once 1 infested block is broken by a player, more silverfish will break their own blocks and swarm the player<p>Can infest cobblestone, deepslate and all their varients</p></td></tr>" +
    /* Skeleton */"<tr><td><img src='/images/skeleton.jpg' alt='skeleton'><p>Skeleton</p></td><td>10 hearts</td><td>Hostile</td><td>Light level 0<p>Mob spawner in a dungeon</p><p>Trial spawner in a trial chamber</p></td><td>Can spawn on top off a spider to create a spider jockey<p>Burn in daylight</p></td></tr>" +
    /* Slime */"<tr><td><img src='/images/slime.jpg' alt='slime'><p>Slime</p></td><td>8 hearts (big)<p>2 hearts (medium)</p><p>0.5 hearts (small)</p></td><td>Hostile</td><td>Swamp, mangrove swamp & slime chunks<p>Trial spawners from trial chambers</p><p>When an entity with the oozing effect dies</p></td><td>Small slimes deal no damage when they attack a player</td></tr>" +
    /* Sniffer */"<tr><td><img src='/images/sniffer.jpg' alt='sniffer'><p>Sniffer</p></td><td>7 hearts</td><td>Passive</td><td>When a sniffer egg hatches, they don't naturally spawn anywhere</td><td>Can sniff out torchflower and pitcherpod seeds</td></tr>" +
    /* Snow Golem*/"<tr><td><img src='/images/snowGolem.jpg' alt='snow golem'><p>Snow Golem</p></td><td>2 hearts</td><td>Passive</td><td>Created by stacking 2 snow blocks then a carved pumpkin</td><td>Will die in desert, mesa and savanna unless given fire resistance<p>Will take damage and eventually die in rain and water</p><p>Will move towards and attack monsters</p></td></tr>" +
    /* Spider */"<tr><td><img src='/images/spider.jpg' alt='spider'><p>Spider</p></td><td>8 hearts</td><td>Hostile in light level 11 and under<p>Neutral in light level 12 and under</p></td><td>Light level 0<p>mob spawners in dungeons and woodland mansions</p><p>trial spawners in trial chambers</p></td><td>Can climb walls<p></p></td></tr>" +
    /* Squid */"<tr><td><img src='/images/squid.png' alt='squid'><p>Squid</p></td><td>5 hearts</td><td>Passive</td><td> From y-level 50-63 in any river or ocean biome varient</td><td>Squirts ink at an attacking entity and swims away very quickly</td></tr>" +
    /* Stray */"<tr><td><img src='/images/stray.jpg' alt='stray'><p>Stray</p></td><td>10 hearts</td><td>Hostile</td><td>Snowy plains & ice spikes<p>Trial spawners from Trial Chambers</p><p>When a skeleton freezes</p></td><td>Shoots arrows tipped with slowness</td></tr>" +
    /* Tropical Fish */"<tr><td><img src='/images/tropicalFish.jpg' alt='tropical fish'><p>Tropical Fish</p></td><td>1.5 hearts</td><td>Passive</td><td>Mangrove swamp, lukewarm ocean, deep lukewarm ocean, warm ocean & lush caves</td><td>Can be picked up in a bucket<p>3,072 different naturally occuring tropical fish</p></td></tr>" +
    /* Turtle */"<tr><td><img src='/images/turtle.jpg' alt='turtle'><p>Turtle</p></td><td>15 hearts</td><td>Passive</td><td>Beach with light level 9 and over</td><td>Can drop turtle scutes when they grow into adults<p>Most hostile and some neutral and passive mobs will attack turtle eggs and baby turtles</p></td></tr>" +
    /* Villager */"<tr><td><img src='/images/villagers.jpg' alt='villager'><p>Villager</p></td><td>10 hearts</td><td>Passive</td><td>Village<p>Igloo basement</p></td><td>Can trade for/with a wide varity of things<p>If killed by a zombie or zombie villagers, there's a small chance the villager will turn into a zombie villager</p></td></tr>" +
    /* Vindicator */"<tr><td><img src='/images/vindicator.jpg' alt='vindicator'><p>Vindicator</p></td><td>12 hearts</td><td>Hostile</td><td>Woodland mansions & raids</td><td>Drops emeralds when killed</td></tr>" +
    /* Wandering Trader */"<tr><td><img src='/images/wanderingTrader.jpg' alt='wandering trader'><p>Wandering Trader</p></td><td>10 hearts</td><td>Passive</td><td>Attempts to spawns close to a random player every 20 minutes or 1 in-game day</td><td>Drinks an invisability potion when it starts to become night</td></tr>" +
    /* Warden */"<tr><td><img src='/images/warden.jpg' alt='warden'><p>Warden</p></td><td>250 hearts</td><td>Hostile</td><td>A player sets off naturally-generated shriekers 4 times and every time after that</td><td>Are blind, listen and smell for the player<p>Can attack with a sonic blast that travels through walls and other entities to its target</p></td></tr>" +
    /* Witch*/"<tr><td><img src='/images/witch.jpg' alt='witch'><p>Witch</p></td><td>13 hearts</td><td>Hostile</td><td>When light level is 0<p>Inside a swamp hut</p><p>As part of raids</p><p>When lighting strikes a villager</p></td><td>Attacks and heals with potions. Has a small chance to drop a potion if killed while drinking one</td></tr>" +
    /* Wolf */"<tr><td><img src='/images/wolves.webp' alt='wolf'><p>Wolf</p></td><td>4 hearts (wild)<p>20 hearts (tamed)</p></td><td>Neutral<p>Passive to owner if tamed</p><p>Hostile to foxes, sheep, rabbits, baby turtles & skeletons</p></td><td>Forest, grove, old growth pine taiga, old growth spruce taiga, savanna plateau, snowy taiga, taiga & wooded badlands</td><td>Can put armor on tamed wolf and they won't take damage until the armor breaks</td></tr>" +
    /* Zombie */"<tr><td><img src='/images/zombie.jpg' alt='zombie'><p>Zombie</p></td><td>10 hearts</td><td>Hostile</td><td>With light level 0<p>Mob spawners from dungeons</p><p>Trial spawners in Trial Chambers</p></td><td>Baby zombies can spawn on top of chickens to create chicken jockeys<p>Burns in daylight</p></td></tr>" +
    /* Zombie Villager */"<tr><td><img src='/images/zombieVillager.jpg' alt='zombie villager'><p>Zombie Villager</p></td><td>10 hearts</td><td>Hostile</td><td>When light level at 0</td><td>Can be turned back into villagers when the weakness effect is applied and fed a golden apple</td></tr>";
    document.getElementById("f").style.height = "1361vh";
}

function netherFunction() {
    document.getElementById("table").innerHTML =
    /* Titles */"<tr><td>Overworld Mob Picture</td><td>Health</td><td>Aggression Status</td><td>Natural Spawn</td><td>Other Info</td></tr>" +
    /* Blaze */"<tr><td><img src='/images/blaze.jpg' alt='blaze'><p>Blaze</p></td><td>10 hearts</td><td>Hostile</td><td> Nether fortress (light level 11 and below or from mob spawners</td><td>Immune to fire and lava damage<p>Drops blaze rods when killed</p></td></tr>" +
    /* Ghast */"<tr><td><img src='/images/ghast.jpg' alt='ghast'><p>Ghast</p></td><td>10 hearts</td><td>Hostile</td><td>Nether wastes, soul sand valley & basalt deltas</td><td>Shoots fireballs when it sees a player<p>Can drop ghast tears and gunpowder when killed</p></td></tr>" +
    /* Hoglin */"<tr><td><img src='/images/hoglin.jpg' alt='hoglin'><p>Hoglin</p></td><td>20 hearts</td><td>Hostile</td><td>Bastion remnant & crimson forest</td><td>Scared of warped fungi, active nether portals & respawn anchors<p>Its attacks can throw entities a little bit up in the air</p></td></tr>" +
    /* Magama Cube */"<tr><td><img src='/images/magmaCube.jpg' alt='magma cube'><p>Magma Cube</p></td><td>8 hearts (big)<p>2 hearts (medium)</p><p>0.5 hearts (small)</p></td><td>Hostile</td><td>Basalt deltas, nether fortress & nether wastes<p>Mob spawners in bastion remnant</p></td><td>Drops magma cream when killed</td></tr>" +
    /* Piglin */"<tr><td><img src='/images/piglin.jpg' alt='piglin'><p>Piglin</p></td><td> </td><td>Neutral (if player is wearing gold)</td><td>bastion remnant, crimson forest & nether wastes</td><td>Turns hostile if player attacks a piglin or mines gold too close to a piglin</td></tr>" +
    /* Piglin Brute */"<tr><td><img src='/images/piglinBrute.jpg' alt='piglin brute'><p>Piglin Brute</p></td><td>25 hearts</td><td>Hostile</td><td>Bastion remnant</td><td>Always spawns with a gold axe and is always hostile with players even if they're wearing gold</td></tr>" +
    /* Wither Skeleton */"<tr><td><img src='/images/witherSkeleton.jpg' alt='wither skeleton'><p>Wither Skeleton</p></td><td>10 hearts</td><td>Hostile</td><td>Nether fortress</td><td>Applies wither effect when attacking other entities<p>Can walk through wither roses without gaining the wither effect</p></td></tr>";
    document.getElementById("f").style.height = "190vh";
}

function endFunction() {
    document.getElementById("table").innerHTML =
    /* Titles */"<tr><td>Overworld Mob Picture</td><td>Health</td><td>Aggression Status</td><td>Natural Spawn</td><td>Other Info</td></tr>" +
    /* Ender Dragon */"<tr><td><img src='/images/enderDragon.jpg' alt='ender dragon'><p>Ender Dragon</p></td><td>100 hearts</td><td>Hostile</td><td>Center island in the End</td><td>Heals from end crystals<p>Once killed, drops a lot of XP and opens the End portal if the dragon was spawned in the End</p></td></tr>" +
    /* Shulker */"<tr><td><img src='/images/shulker.jpg' alt='shulker'><p>Shulker</p></td><td>15 hearts</td><td>Hostile</td><td>End city</td><td>Shoots crystals that track a player and give levetation effect when they hit the player<p>Can teleport if it takes too much damage</p></td></tr>";
    document.getElementById("f").style.height = "62vh";
}

overworldFunction(); /*sets default to overworld*/

const background = document.getElementById("scrollBackground");

window.addEventListener("scroll", () => {
    let scrollY = window.scrollY;
    let newHeight = Math.max(0, 200 - scrollY);
    background.style.height = `${newHeight}px`;
});
